### ISSUE TITLE
Entropy devided by Log(2)

### ISSUE THREAD

**Issue by NickGeneva** [cics-nd/pde-surrogate#2]
Where does the math.log(2) come from [when calculating the entropy term](https://github.com/cics-nd/pde-surrogate/blob/master/train_cglow_reverse_kl.py#L185).

`neg_entropy = log_likeihood.mean() / math.log(2.) / n_out_pixels`

Just want to confirm this is correct.

**Comment by yinhaoz** [comment]
entropy here uses bit as unit, the base for log is 2.
